#!/bin/sh

# Alias
alias q='exit'
alias v='nvim'
#alias purge='sudo apt purge'
alias ls='ls --color'
alias la='ls -la'
alias ll='ls -l'
alias py='python3'
alias source_all='source ~/.zshenv && source ~/.config/zsh/.zshrc && source ~/.config/zsh/alias && source ~/.config/zsh/functions'

# Complete update system
if command -v apt >/dev/null 2>&1; then
    alias up='sudo apt update && sudo apt upgrade -y && flatpak update -y'
else
    alias up='sudo dnf upgrade -y && flatpak update -y'
fi

# Remove Package command
if command -v apt >/dev/null 2>&1; then
    alias remove='sudo apt remove'
else
    alias remove='sudo dnf remove'
fi

# Autoremove Package command
if command -v apt >/dev/null 2>&1; then
    alias autoremove='sudo apt autoremove'
else
    alias autoremove='sudo dnf autoremove'
fi

# Update Package command
if command -v apt >/dev/null 2>&1; then
    alias update='sudo apt update'
else
    alias update='sudo dnf update'
fi

# Upgrade Package command
if command -v apt >/dev/null 2>&1; then
    alias upgrade='sudo apt upgrade'
else
    alias upgrade='sudo dnf upgrade'
fi

# Install Package command
if command -v apt >/dev/null 2>&1; then
    alias install='sudo apt install'
else
    alias install='sudo dnf install'
fi


if command -v eza >/dev/null 2>&1; then
    alias ls='eza -gh'
else
    alias ls='exa -gh'
fi

# Battery command
if command -v upower >/dev/null 2>&1; then
    bat_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
    if [[ $bat_info == *"unknown"* ]]; then
        alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT1'
    else
        alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0'
    fi
else
    alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT1'
fi

# Backup alias
backup() {
    trap 'unset location' EXIT INT TERM
    
    if [ -z "$1" ]; then
        read -p "Please provide a backup location: " location
    else
        location=$1
    fi

    if [ ! -d "$location" ]; then
        echo "Error: $location is not a valid directory."
        return 1
    fi
  
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/Nextcloud "$location/Backups" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/Downloads "$location/Backups" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.vscode-oss "$location/Backups" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/Games "$location/Backups/.local" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/share/fonts "$location/Backups/.local/share" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/share/ssh "$location/Backups/.local/share" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/tmp "$location/Backups/.local" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/VMshare "$location/Backups/.local" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.local/history "$location/Backups/.local" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/com.atlauncher.ATLauncher "$location/Backups/.var/app" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/com.realm667.Wolfenstein_Blade_of_Agony "$location/Backups/.var/app" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/org.diasurgical.DevilutionX "$location/Backups/.var/app" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/org.gnome.TwentyFortyEight "$location/Backups/.var/app" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/org.kde.kmymoney "$location/Backups/.var/app" &&
    rsync -r -t -p -o -g -v --progress --delete -s $HOME/.var/app/org.zdoom.GZDoom "$location/Backups/.var/app"
}


