#!/bin/sh

# Alias
alias q='exit'
alias v='nvim'
alias up='sudo apt update && sudo apt upgrade -y && flatpak update -y'
alias update='sudo apt update'   
alias upgrade='sudo apt upgrade'
alias autoremove='sudo apt autoremove'
alias remove='sudo apt remove'
alias install='sudo apt install'
alias neo='neofetch'
alias ls='exa'
alias la='ls -la'
alias ll='ls -l'
alias fltheme='sudo flatpak override --env=GTK_THEME'
alias backup='rsync -r -t -p -o -g -v --progress --delete -s /home/sacra/Documents /mnt/Ba      ckups/Backups/ && rsync -r -t -p -o -g -v --progress --delete -s /home/sacra/Music /mnt/Ba      ckups/Backups/ && rsync -r -t -p -o -g -v --progress --delete -s /home/sacra/Pictures /mnt      /Backups/Backups/'
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full      |percentage"'
alias flatpak='flatpak --user'
