#!/bin/bash

# Ranger
r() {
  ranger --choosedir=$HOME/.rangerdir;
  LASTDIR=`cat $HOME/.rangerdir`;
  cd "$LASTDIR";
  rm $HOME/.rangerdir
}
 bindkey -s '^o' 'r\n'

# Use modern completion system
autoload -Uz compinit
compinit

# Basic auto/tab complete
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)	

# Generating flatpak alias cache file
generate_flatpak_alias_cache() {
  mkdir -p ~/.cache
  echo "# Regenerating Flatpak alias cache..."
  ~/Nextcloud/repo/bin/.dotfiles/.local/bin/.zsh_flatpak_cache_gen.sh > ~/.cache/zsh_flatpak_cache.zsh
}