#!/bin/sh
echo "# Autogenerated Flatpak alias cache"

echo 'flatpak_aliases=('
flatpak list --app --columns=application | awk -F '.' '
{
  app_id = $0
  short_name = $NF
  printf "  \"%s:%s\"\n", short_name, app_id
}'
echo ')'

cat << 'EOF'
for entry in "${flatpak_aliases[@]}"; do
  cmd="${entry%%:*}"
  appid="${entry#*:}"
  if ! command -v "$cmd" >/dev/null; then
    eval "function $cmd() { flatpak run $appid \"\$@\"; }"
  fi
done
EOF
