# alacritty.toml
# commented lines are the defaults

import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
padding               = { x = 2, y = 2 }
#dynamic_padding       = true
decorations           = "None"
opacity               = 1.0
blur                  = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"


[scrolling]
history               = 65535
#multiplier            = 3

[font]
#normal                = { family = "FantasqueSansMNerdFont Propo", style = "Regular" }
#bold                  = { family = "FantasqueSansMNerdFont Propo", style = "Bold" }
#italic                = { family = "FantasqueSansMNerdFont Propo", style = "Italic" }
#bold_italic           = { family = "FantasqueSansMNerdFont Propo", style = "Bold Italic" }
size                  = 14
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

#transparent_background_colors = false
# draw_bold_text_with_bright_colors = true

#[bell]
#animation             = "EaseOutExpo"
#duration              = 0
#color                 = "#C0C5CE"
#command               = { program = "notify-send", args = ["alacritty", "bell",] }

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
#blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

#render_timer          = false
#persistent_logging    = false
#log_level             = "Warn"
#renderer              = "None"
#print_events          = false
#highlight_damage      = false
#prefer_egl            = false
